/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("edu.sc.seis.launch4j") version "4.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation ("org.xerial:sqlite-jdbc:3.46.1.0")
    implementation ("se.michaelthelin.spotify:spotify-web-api-java:9.3.0")
    implementation ("com.google.code.gson:gson:2.11.0")
    implementation ("io.github.cdimascio:dotenv-java:3.0.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application { 
    // Define the main class for the application.
    mainClass.set("hitmaster.Main")
}

javafx {
    version = "21"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.media", "javafx.swing")
}

tasks.shadowJar {
    archiveClassifier.set("all")
    manifest {
        attributes["Main-Class"] = "hitmaster.Main"
    }
}

launch4j {
    outputDir.set(layout.buildDirectory.dir("distributions").get().asFile.absolutePath)
    outfile.set("HitMaster.exe")
    
    setJarTask(tasks.shadowJar.get())
    
    mainClassName.set("hitmaster.Launcher")
    dontWrapJar.set(false)
    
    headerType.set("gui")
    jreMinVersion.set("21")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
